// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXQJUg4qzYKgs78u3KCe7XFhy2MUYpKw',
    appId: '1:329450121649:web:08b033d1fbb82891a57590',
    messagingSenderId: '329450121649',
    projectId: 'dm-tarl',
    authDomain: 'dm-tarl.firebaseapp.com',
    databaseURL: 'https://dm-tarl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dm-tarl.firebasestorage.app',
    measurementId: 'G-GVXNF5M221',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXm-BkTTBLfk5LdMTNWsFwX8ogS2jeuig',
    appId: '1:329450121649:android:f1cf5caca94876a9a57590',
    messagingSenderId: '329450121649',
    projectId: 'dm-tarl',
    databaseURL: 'https://dm-tarl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dm-tarl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHonnHXvaw5Ypyj2I-ABYzez_wKTeOiC8',
    appId: '1:329450121649:ios:eddaae34925d74b9a57590',
    messagingSenderId: '329450121649',
    projectId: 'dm-tarl',
    databaseURL: 'https://dm-tarl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dm-tarl.firebasestorage.app',
    androidClientId: '329450121649-be4areao19kqp8cdknpmelj71glhtlmq.apps.googleusercontent.com',
    iosClientId: '329450121649-ob17qhoucot0pq0b2h4bam88vsel92m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarlMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHonnHXvaw5Ypyj2I-ABYzez_wKTeOiC8',
    appId: '1:329450121649:ios:eddaae34925d74b9a57590',
    messagingSenderId: '329450121649',
    projectId: 'dm-tarl',
    databaseURL: 'https://dm-tarl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dm-tarl.firebasestorage.app',
    androidClientId: '329450121649-be4areao19kqp8cdknpmelj71glhtlmq.apps.googleusercontent.com',
    iosClientId: '329450121649-ob17qhoucot0pq0b2h4bam88vsel92m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarlMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVXQJUg4qzYKgs78u3KCe7XFhy2MUYpKw',
    appId: '1:329450121649:web:31a3857e9e08b2d0a57590',
    messagingSenderId: '329450121649',
    projectId: 'dm-tarl',
    authDomain: 'dm-tarl.firebaseapp.com',
    databaseURL: 'https://dm-tarl-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dm-tarl.firebasestorage.app',
    measurementId: 'G-J1MXY8TV34',
  );
}
